import bcrypt from "bcrypt";

export const data = {
  users: [
    {
      name: "Oscar",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Nike Slim Fit Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Loose Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 15,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Fit Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 0,
      brand: "Nike",
      rating: 3.5,
      numReviews: 8,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 12,
      brand: "Puma",
      rating: 4.2,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 55,
      countInStock: 3,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
  ],
};
